# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f91e3cb2-8903-42cd-ac7d-b031b4440f4c";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/f91e3cb2-8903-42cd-ac7d-b031b4440f4c";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/f91e3cb2-8903-42cd-ac7d-b031b4440f4c";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/f91e3cb2-8903-42cd-ac7d-b031b4440f4c";
    fsType = "btrfs";
    options = [ "subvol=@log" ];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/disk/by-uuid/f91e3cb2-8903-42cd-ac7d-b031b4440f4c";
    fsType = "btrfs";
    options = [ "subvol=@snapshots" ];
  };

  fileSystems."/vm" = {
    device = "/dev/disk/by-uuid/f91e3cb2-8903-42cd-ac7d-b031b4440f4c";
    fsType = "btrfs";
    options = [ "subvol=@vm" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D2B9-E2BF";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
